services:
  playground-macos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_ADMIN_PASSWORD: ${VITE_ADMIN_PASSWORD}
        VITE_API_URL: ${VITE_API_URL}
        VITE_OPENWEATHER_API_KEY: ${VITE_OPENWEATHER_API_KEY}
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    container_name: playground-macos
